### ISSUE TITLE
Detail of the test

### ISSUE THREAD

**Issue by laiviet** [dsdanielpark/Open-LLM-Leaderboard-Report#1]
Hi,

Thanks for working on this. Would you share more about the detail of the metrics and the task for each dataset?
For example, TruthfulQA has multiple choice and generation tasks, each using some metrics.

Thanks,
VIet

**Comment by dsdanielpark** [comment]
Hi,

All experiments were conducted in Hugging Face's Docker environment called "space." Additionally, you can compile your model as well. For more detailed information, please check the following link!

The images in this repository are used as the background data for the results on the following page.

https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

**Comment by laiviet** [comment]
I think you misunderstood my question.
The question is:
What are the metrics used to report in the open LLM leaderboard?
Are they accuracy/accuracy_norm/bleu/rouge/bleurt?
Each dataset mentioned in the leaderboard has multiple subtasks, which subtasks does this leaderboard actually refer to?

**Comment by dsdanielpark** [comment]
As I mentioned above, you can check at here.

https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/blob/main/utils.py

```python
LMEH_REPO = "HuggingFaceH4/lmeh_evaluations"

METRICS = ["acc_norm", "acc_norm", "acc_norm", "mc2"]
BENCHMARKS = ["arc_challenge", "hellaswag", "hendrycks", "truthfulqa_mc"]
BENCH_TO_NAME = {
    "arc_challenge":"ARC (25-shot) ⬆️",
     "hellaswag":"HellaSwag (10-shot) ⬆️",
     "hendrycks":"MMLU (5-shot) ⬆️",
     "truthfulqa_mc":"TruthfulQA (0-shot) ⬆️",
}



...



   
def parse_eval_result(json_filepath: str) -> Tuple[str, dict]:
    with open(json_filepath) as fp:
        data = json.load(fp)

    path_split = json_filepath.split("/")
    org = None
    model = path_split[-4]
    is_8bit = path_split[-2] == "8bit"
    revision = path_split[-3]
    if len(path_split)== 7:
        # handles gpt2 type models that don't have an org
        result_key = f"{path_split[-4]}_{path_split[-3]}_{path_split[-2]}"
    else:
        result_key = f"{path_split[-5]}_{path_split[-4]}_{path_split[-3]}_{path_split[-2]}"
        org = path_split[-5]
        
    eval_result = None
    for benchmark, metric  in zip(BENCHMARKS, METRICS):
        if benchmark in json_filepath:
            accs = np.array([v[metric] for k, v in data["results"].items()])
            mean_acc = round(np.mean(accs)*100.0,1)
            eval_result = EvalResult(result_key, org, model, revision, is_8bit, {benchmark:mean_acc})
        
    return result_key, eval_result

```



In the evaluation of LLM (Language Model), there are various metrics available to assess the model's performance. However, the most reliable approach is to check eval code and eval dataset.

**Comment by laiviet** [comment]
Thank you for pointing this out. I didn't know that it has source code behind it. I really appreciate your prompt response.
Close the issue because the problem is solved.
